/**
 * Strings for the signed Terms-of-Access PDF.
 *
 * The certificate is written in the language the evaluator actually signed
 * in — a Japanese signer should not receive a Japanese contract wrapped in
 * English scaffolding. As elsewhere, `en` is the typed source of truth and
 * `ja` must satisfy exactly that shape.
 */

import type { Locale } from "./locales";

const en = {
  brand: "POCX · ELECTRONIC SIGNATURE RECORD",
  title: (pocName: string) => `${pocName} — Terms of Access`,
  subtitle: (p: { version: string; ownerEntity: string }) =>
    `Version ${p.version} · accepted electronically via the POCX access gate operated for ${p.ownerEntity}`,
  docTitle: (pocName: string) => `${pocName} — Terms of Access (signed)`,
  docAuthor: (ownerEntity: string) => `POCX for ${ownerEntity}`,
  recordHeading: "Signature record",
  signatureId: "Signature id",
  signedByName: "Signed by (typed name)",
  signedByEmail: "Signed by (email)",
  acceptedAt: "Accepted at (UTC)",
  ip: "IP address",
  browser: "Browser",
  hash: "Terms hash (SHA-256)",
  language: "Language signed",
  termsHeading: "Terms as shown to the signer",
  footer:
    "Generated by POCX — the access layer for proofs of concept. The SHA-256 hash above is computed over the exact terms text reproduced in this document.",
};

const ja: typeof en = {
  brand: "POCX · 電子署名記録",
  title: (pocName: string) => `${pocName} — アクセス利用規約`,
  subtitle: (p: { version: string; ownerEntity: string }) =>
    `バージョン${p.version} · ${p.ownerEntity}のために運用されるPOCXアクセスゲートを通じて電子的に同意されました`,
  docTitle: (pocName: string) => `${pocName} — アクセス利用規約（署名済み）`,
  docAuthor: (ownerEntity: string) => `POCX（${ownerEntity}向け）`,
  recordHeading: "署名記録",
  signatureId: "署名ID",
  signedByName: "署名者（入力された氏名）",
  signedByEmail: "署名者（メールアドレス）",
  acceptedAt: "同意日時（UTC）",
  ip: "IPアドレス",
  browser: "ブラウザ",
  hash: "規約ハッシュ（SHA-256）",
  language: "署名した言語",
  termsHeading: "署名者に表示された規約本文",
  footer:
    "本書はPOCX（概念実証のためのアクセス基盤）により生成されました。上記のSHA-256ハッシュ値は、本書に再現された規約本文そのものから算出されています。",
};

/** Human name of the language the terms were signed in. */
export const LOCALE_LABELS: Record<Locale, string> = {
  en: "English",
  ja: "日本語 (Japanese)",
};

export const pdfDict: Record<Locale, typeof en> = { en, ja };
