import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

/**
 * Signed Terms-of-Access certificate. Rendered server-side at acceptance
 * time, stored beside the DB and emailed to the signer. The document
 * reproduces the exact terms text plus the evidentiary metadata (who,
 * when, from where, hash of what was shown).
 */

export type SignaturePdfProps = {
  pocName: string;
  ownerEntity: string;
  signatureId: string;
  email: string;
  acceptedAtUtc: string;
  ip: string;
  userAgent: string;
  termsVersion: string;
  termsHashHex: string;
  termsParagraphs: string[];
};

const styles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 56,
    paddingHorizontal: 52,
    fontSize: 9.5,
    fontFamily: "Helvetica",
    color: "#16161f",
    lineHeight: 1.5,
  },
  brand: {
    fontSize: 10,
    letterSpacing: 2,
    color: "#D4551A",
    fontFamily: "Helvetica-Bold",
    marginBottom: 2,
  },
  title: { fontSize: 16, fontFamily: "Helvetica-Bold", marginBottom: 2 },
  subtitle: { fontSize: 10, color: "#4b4b58", marginBottom: 18 },
  h2: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginTop: 16,
    marginBottom: 6,
  },
  para: { marginBottom: 7 },
  metaBox: {
    borderWidth: 1,
    borderColor: "#c9c9d2",
    borderRadius: 6,
    padding: 12,
    marginTop: 6,
    backgroundColor: "#f8f8fa",
  },
  metaRow: { flexDirection: "row", marginBottom: 3 },
  metaKey: { width: 130, color: "#4b4b58" },
  metaVal: { flex: 1, fontFamily: "Helvetica-Bold" },
  mono: { fontFamily: "Courier", fontSize: 8 },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 52,
    right: 52,
    fontSize: 8,
    color: "#6e6e7a",
    textAlign: "center",
  },
});

export function SignaturePdf(props: SignaturePdfProps) {
  return (
    <Document
      title={`${props.pocName} — Terms of Access (signed)`}
      author={`POCX for ${props.ownerEntity}`}
    >
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>POCX · ELECTRONIC SIGNATURE RECORD</Text>
        <Text style={styles.title}>
          {props.pocName} — Terms of Access
        </Text>
        <Text style={styles.subtitle}>
          Version {props.termsVersion} · accepted electronically via the POCX
          access gate operated for {props.ownerEntity}
        </Text>

        <Text style={styles.h2}>Signature record</Text>
        <View style={styles.metaBox}>
          <View style={styles.metaRow}>
            <Text style={styles.metaKey}>Signature id</Text>
            <Text style={styles.metaVal}>{props.signatureId}</Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={styles.metaKey}>Signed by (email)</Text>
            <Text style={styles.metaVal}>{props.email}</Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={styles.metaKey}>Accepted at (UTC)</Text>
            <Text style={styles.metaVal}>{props.acceptedAtUtc}</Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={styles.metaKey}>IP address</Text>
            <Text style={styles.metaVal}>{props.ip}</Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={styles.metaKey}>Browser</Text>
            <Text style={[styles.metaVal, { fontFamily: "Helvetica" }]}>
              {props.userAgent}
            </Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={styles.metaKey}>Terms hash (SHA-256)</Text>
            <Text style={[styles.metaVal, styles.mono]}>
              {props.termsHashHex}
            </Text>
          </View>
        </View>

        <Text style={styles.h2}>Terms as shown to the signer</Text>
        {props.termsParagraphs.map((p, i) => (
          <Text key={i} style={styles.para}>
            {p}
          </Text>
        ))}

        <Text style={styles.footer} fixed>
          Generated by POCX — the access layer for proofs of concept. The
          SHA-256 hash above is computed over the exact terms text reproduced
          in this document.
        </Text>
      </Page>
    </Document>
  );
}
